config/routes.rb
Rails.application.routes.draw do

  get 'linkedin/people'
  get 'linkedin/companies'

  resources :organizations do
    resources :memberships
    resources :lists do
      resources :leads
    end
  end

  resources :users do
    resources :oauths
  end

  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/linkedin/new', to: 'sessions#new_linkedin_auth'
  
  root 'welcome#index'
  get '/home', to: 'welcome#home'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :organization
  belongs_to :creator, class_name: 'User' # Creator of this list
  
  has_many :leads, dependent: :destroy
  
  validates :organization, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false, scope: :organization_id }
  validates :permalink, presence: true, uniqueness: { case_sensitive: false }
  validates :creator, presence: true
  
  before_validation :autofill_permalink_if_blank
  
  def to_param
    self.permalink
  end
  
  def autofill_permalink_if_blank
    return true unless self.permalink.blank? # Bypass if permalink is already set
    self.permalink = AutoPermalink::cleaned_deduped_permalink(self.class, self.name)
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_organization
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_filter :enforce_auth
  before_filter :set_authed_user_membership
  before_filter :enforce_can_read, only: [:index, :show]
  before_filter :enforce_can_write, only: [:new, :create, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = @organization.lists.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = @organization.lists.build(creator: authed_user)
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = @organization.lists.build(list_params.merge(creator: authed_user))

    respond_to do |format|
      if @list.save
        format.html { redirect_to [@list.organization, @list], notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: [@list.organization, @list] }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to [@list.organization, @list], notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: [@list.organization, @list] }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to organization_lists_url(@organization), notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = authed_user.organizations.find_by_permalink(params[:organization_id])
      raise ActiveRecord::RecordNotFound unless @organization
    end

    def set_authed_user_membership
      @set_authed_user_membership = @organization.memberships.where(user_id: authed_user.id).first
      raise ActiveRecord::RecordNotFound unless @set_authed_user_membership
    end

    def enforce_can_read
      if !@set_authed_user_membership.read?
        render :text => "Sorry, you aren't authorized to access this page.", :status => :unauthorized
        return false
      else
        return true
      end
    end

    def enforce_can_write
      if !@set_authed_user_membership.write?
        render :text => "Sorry, you aren't authorized to access this page.", :status => :unauthorized
        return false
      else
        return true
      end
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = @organization.lists.find_by_permalink(params[:id])
      raise ActiveRecord::RecordNotFound unless @list
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :permalink, :description, :picurl)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for([@list.organization, @list]) do |f| %>
<% if @list.errors.any? %>
<div id="error_explanation" class="alert alert-danger" role="alert">
	<strong><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</strong>

	<ul>
		<% @list.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>


<div class="row">
	<div class="form-group<%= f.object.errors[:name].empty? ? "" : " has-error has-feedback" %>">
		<%= f.label :name, { class: "control-label col-sm-2" } %>
		<div class="col-sm-10">
			<%= f.text_field :name, { class: "form-control title-control", autofocus: 'autofocus', placeholder: "List Name" } %>
		</div>
	</div>
</div>

<% if !f.object.new_record? %>
<div class="row">
	<div class="form-group<%= f.object.errors[:permalink].empty? ? "" : " has-error has-feedback" %>">
		<%= f.label :permalink, { class: "control-label col-sm-2" } %>
		<div class="col-sm-10">
			<%= f.text_field :permalink, { class: "form-control" } %>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group<%= f.object.errors[:description].empty? ? "" : " has-error has-feedback" %>">
		<%= f.label :description, { class: "control-label col-sm-2" } %>
		<div class="col-sm-10">
			<%= f.text_field :description, { class: "form-control" } %>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group<%= f.object.errors[:picurl].empty? ? "" : " has-error has-feedback" %>">
		<%= f.label :picurl, { class: "control-label col-sm-2" } %>
		<div class="col-sm-10">
			<%= f.text_field :picurl, { class: "form-control" } %>
		</div>
	</div>
</div>
<% end %>

<div class="actions text-center">
	<%= f.submit class: "btn btn-success" %>
</div>
<% end %>

app/views/lists/edit.html.erb
<% content_for :page_title do %>
Edit List - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>Editing List</h1>
	</div>

	<%= render 'form' %>

	<div class="clearfix"></div>
	<div class="pull-left">
		<%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, [@list.organization, @list], class: "btn btn-default" %>
	</div>
	<div class="pull-right">
		<%= link_to "<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> Delete list...".html_safe, [@list.organization, @list], method: :delete, data: { confirm: "Are you sure you want to delete this list?" }, class: "btn btn-danger" %>
	</div>
</div>

app/views/lists/index.html.erb
<% content_for :page_title do %>
Lists - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>
			<div class="pull-left">
				<%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, @organization, class: "btn btn-default", title: "Back" %>
				&nbsp;
			</div>

			<div class="pull-right">
				<%= link_to "<span class=\"glyphicon glyphicon-plus-sign\" aria-hidden=\"true\"></span> New List".html_safe, [:new, @organization, :list], class: "btn btn-success" %>
			</div>
			Listing Lists
		</h1>
	</div>

	<table class="table table-striped table-hover tablesorter" id="Lists-table">


		<thead>
			<tr>
				<th><span></span></th>
				<th><span>Name</span></th>
				<th><span>Description</span></th>
				<th><span>Added</span></th>
				<th><span>By</span></th>
			</tr>
		</thead>

		<tbody>
			<% unless @lists.any? %>
			<tr id="empty-table">
				<td class="bg-warning" colspan="2">No lists created yet.</td>
			</tr>
			<% end %>
			<% @lists.each do |list| %>
			<tr class="linked-row" data-href="<%= organization_list_path(list.organization, list) %>">
				<td><% unless list.picurl.blank? %><%= link_to image_tag(list.picurl).html_safe, [list.organization, list] %><% end %></td>
				<td><%= link_to list.name, [list.organization, list] %></td>
				<td><%= link_to list.description.blank? ? '[none]' : list.description, [list.organization, list] %></td>
				<td><%= link_to "#{distance_of_time_in_words_to_now list.created_at} ago", [list.organization, list] %> </td>
				<td><%= link_to list.creator.full_name, [list.organization, list] %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/lists/new.html.erb
<% content_for :page_title do %>
Create List - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>
			New List
		</h1>
	</div>

	<%= render 'form' %>

	<div class="clearfix"></div>
	<%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, organization_lists_path(@organization), class: "btn btn-default" %>
</div>

app/views/lists/show.html.erb
<% content_for :page_title do %>
List Details - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>
			<div class="pull-left">
				<%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, organization_lists_path(@list.organization), class: "btn btn-default", title: "Back to lists" %>
				&nbsp;
			</div>
			<div class="pull-right">
				<%= link_to "<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> Edit".html_safe, edit_organization_list_path(@list.organization, @list), class: "btn btn-warning" %>
			</div>
			
			<% unless @list.picurl.blank? %>
				<%= image_tag(@list.picurl) %>
			<% end %>
			
			List Details
		</h1>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Name</label>
		<div class="col-sm-9"><%= @list.name %></div>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">&nbsp;</label>
		<div class="col-sm-9"><small><span class="text-muted"><%= organization_lists_url(@organization) %>/</span><%= @list.permalink %> (<%= link_to 'link', [@list.organization, @list] %>)</small></div>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Description</label>
		<div class="col-sm-9"><%= @list.description.blank? ? '<span class="text-muted">[none]</span>'.html_safe : @list.description %></div>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Member Since</label>
		<div class="col-sm-9"><%= distance_of_time_in_words_to_now @list.created_at %> ago</div>
	</div>
	<div class="row">
		<label class="col-sm-3 text-right text-muted">Added By</label>
		<div class="col-sm-9"><%= @list.creator.full_name %></div>
	</div>
	
	
	<div>
		<h2>
			<div class="pull-right">
				<a href="<%= new_organization_list_lead_path(@list.organization, @list) %>" class="btn btn-info">Add a Lead</a>
			</div>
			<%= link_to 'Leads', organization_list_leads_path(@list.organization, @list) %> <span class="label label-default"><%= @list.leads.count %></span>
		</h2>
	</div>

</div>