config/routes.rb
Rails.application.routes.draw do

  get 'linkedin/people'
  get 'linkedin/companies'

  resources :organizations do
    resources :memberships
    resources :lists do
      resources :leads
    end
  end

  resources :users do
    resources :oauths
  end

  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/linkedin/new', to: 'sessions#new_linkedin_auth'
  
  root 'welcome#index'
  get '/home', to: 'welcome#home'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  PRIVILEGE_CODES = { read: 'r', read_write: 'rw', read_write_execute: 'rwx' } # modeled after OS privilege codes
  VALID_PRIVILEGES = PRIVILEGE_CODES.values
  
  belongs_to :organization
  belongs_to :user
  belongs_to :creator, class_name: 'User' # Inviter of this person to this org
  
  attr_accessor :user_via_email # Allow membership to be added by email.
  
  validates :organization_id, presence: true, uniqueness: { scope: :user_id }
  validates :user, presence: { message: '- no user account found with that email.  Please have your friend signup for free, first!' }
  validates :privileges, presence: true, inclusion: { in: VALID_PRIVILEGES, message: "%{value} setting is not valid." }
  validates :creator, presence: true
  
  before_validation :set_user_via_email
  
  def set_user_via_email
    return true unless self.user.nil?
    self.user = User.find_by_email(self.user_via_email)
  end
  
  
  # Can read only in this org, and not do anything.
  def read?
    self.privileges == PRIVILEGE_CODES[:read] || self.write?
  end
  
  # Can do stuff within this org
  def write?
    self.privileges == PRIVILEGE_CODES[:read_write] || self.execute?
  end
  
  # Can admin everything in this org
  def execute?
    self.privileges == PRIVILEGE_CODES[:read_write_execute]
  end
  
  def creator_of_org?
    !self.organization.creator_id.to_s.blank? && !self.user_id.to_s.blank? && self.organization.creator_id.to_s == self.user_id.to_s
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_organization
  before_action :set_membership, only: [:show, :edit, :update, :destroy]
  before_filter :enforce_auth
  before_filter :set_authed_user_membership
  before_filter :enforce_can_read, only: [:index, :show]
  before_filter :enforce_can_execute, only: [:new, :create, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = @organization.memberships.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = @organization.memberships.build(creator: authed_user)
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = @organization.memberships.build(membership_params.merge(creator: authed_user))

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = authed_user.organizations.find_by_permalink(params[:organization_id])
      raise ActiveRecord::RecordNotFound unless @organization
    end

    def set_authed_user_membership
      @set_authed_user_membership = @organization.memberships.where(user_id: authed_user.id).first
      raise ActiveRecord::RecordNotFound unless @set_authed_user_membership
    end
  
    def enforce_can_read
      if !@set_authed_user_membership.read?
        render :text => "Sorry, you aren't authorized to access this page.", :status => :unauthorized
        return false
      else
        return true
      end
    end

    def enforce_can_execute
      if !@set_authed_user_membership.execute?
        render :text => "Sorry, you aren't authorized to access this page.", :status => :unauthorized
        return false
      else
        return true
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = @organization.memberships.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:user_via_email, :privileges)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for([@membership.organization,@membership]) do |f| %>
<% if @membership.errors.any? %>
<div id="error_explanation" class="alert alert-danger" role="alert">
	<strong><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</strong>

	<ul>
		<% @membership.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>


<div class="row">
	<div class="form-group<%= f.object.errors[:user_id].empty? ? "" : " has-error has-feedback" %>">
		<%= f.label :user_via_email, 'Team Member\'s Email', { class: "control-label col-sm-2" } %>
		<div class="col-sm-10">
			<%= f.text_field :user_via_email, { class: "form-control", type: 'email', required: 'true' } %>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group<%= f.object.errors[:privileges].empty? ? "" : " has-error has-feedback" %>">
		<%= f.label :privileges, { class: "control-label col-sm-2" } %>
		<div class="col-sm-10">
			<%= f.select :privileges, Membership::PRIVILEGE_CODES.keys.map {|a| [ a.to_s.gsub('_',' & ').titlecase, Membership::PRIVILEGE_CODES[a] ] }, { prompt: '-Select Access Level to Organization-' }, { class: "form-control" } %>
		</div>
	</div>
</div>

<div class="actions text-center">
	<%= f.submit class: "btn btn-success" %>
</div>
<% end %>

app/views/memberships/edit.html.erb
<% content_for :page_title do %>
Edit Membership - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>Editing Membership</h1>
	</div>

	<%= render 'form' %>

	<div class="clearfix"></div>
	<div class="pull-left">
		<%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, [@membership.organization, @membership], class: "btn btn-default" %>
	</div>
	<div class="pull-right">
		<%= link_to "<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> Delete membership...".html_safe, [@membership.organization, @membership], method: :delete, data: { confirm: "Are you sure you want to delete this membership?" }, class: "btn btn-danger" %>
	</div>
</div>

app/views/memberships/index.html.erb
<% content_for :page_title do %>
Memberships - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>
			<div class="pull-left">
				<%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, @organization, class: "btn btn-default", title: "Back" %>
				&nbsp;
			</div>

			<div class="pull-right">
				<%= link_to "<span class=\"glyphicon glyphicon-plus-sign\" aria-hidden=\"true\"></span> New Membership".html_safe, [:new, @organization, :membership], class: "btn btn-success" %>
			</div>
			Listing Memberships
		</h1>
	</div>

	<table class="table table-striped table-hover tablesorter" id="Memberships-table">

		<thead>
			<tr>
				<th><span>User</span></th>
				<th><span>Email</span></th>
				<th><span>Privileges</span></th>
				<th><span>Added</span></th>
				<th><span>By</span></th>
			</tr>
		</thead>

		<tbody>
			<% unless @memberships.any? %>
			<tr id="empty-table">
				<td class="bg-warning" colspan="2">No memberships created yet.</td>
			</tr>
			<% end %>
			<% @memberships.each do |membership| %>
			<tr class="linked-row" data-href="<%= organization_membership_path(membership.organization,membership) %>">
				<td><%= link_to membership.user.full_name, [membership.organization, membership] %></td>
				<td><%= link_to membership.user.email, [membership.organization, membership] %></td>
				<td><%= link_to membership.privileges, [membership.organization, membership] %></td>
				<td><%= link_to "#{distance_of_time_in_words_to_now membership.created_at} ago", [membership.organization, membership] %> </td>
				<td><%= link_to membership.creator.full_name, [membership.organization, membership] %></td>
			</tr>
			<% end %>
		</tbody>
	</table>


</div>

app/views/memberships/new.html.erb
<% content_for :page_title do %>
Add Member - <%= @organization.name %> -
<% end %>
<div class="container">
	<div class="page-header">
		<h1>
			Add a Team Member
		</h1>
	</div>

	<%= render 'form' %>

	<div class="clearfix"></div>
	<%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, organization_memberships_path(@organization), class: "btn btn-default" %>
</div>

app/views/memberships/show.html.erb
<% content_for :page_title do %>
Membership Details - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>
			<div class="pull-left">
				<%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, organization_memberships_path(@organization), class: "btn btn-default", title: "Back to memberships" %>
				&nbsp;
			</div>
			<div class="pull-right">
				<%= link_to "<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> Edit".html_safe, edit_organization_membership_path(@membership.organization, @membership), class: "btn btn-warning" %>
			</div>
			Membership Details
		</h1>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Who</label>
		<div class="col-sm-9"><%= @membership.user.full_name %></div>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Email</label>
		<div class="col-sm-9"><%= link_to "mailto:#{@membership.user.email}", @membership.user.email %></div>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Privileges</label>
		<div class="col-sm-9"><%= @membership.privileges %></div>
	</div>


	<div class="row">
		<label class="col-sm-3 text-right text-muted">Member Since</label>
		<div class="col-sm-9"><%= distance_of_time_in_words_to_now @membership.created_at %> ago</div>
	</div>
	<div class="row">
		<label class="col-sm-3 text-right text-muted">Added By</label>
		<div class="col-sm-9"><%= @membership.creator.full_name %></div>
	</div>

</div>