config/routes.rb
Rails.application.routes.draw do

  get 'linkedin/people'
  get 'linkedin/companies'

  resources :organizations do
    resources :memberships
    resources :lists do
      resources :leads
    end
  end

  resources :users do
    resources :oauths
  end

  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/linkedin/new', to: 'sessions#new_linkedin_auth'
  
  root 'welcome#index'
  get '/home', to: 'welcome#home'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :enforce_auth, only: :home
  
  def index
  end
  
  def home
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Welcome, <%= authed_user.first_name %>.</h1>
	</div>
</div>

<div class="container">
	<h2>
		<div class="pull-right">
			<a href="<%= new_organization_path %>" class="btn btn-info">Create an Organization</a>
		</div>
		Organizations <span class="label label-default"><%= authed_user.organizations.count %></span>
	</h2>
	
	<table class="table table-striped table-hover tablesorter" id="Organizations-table">
		<thead>
			<tr>
				<th><span>Name</span></th>
				<th><span>Lists</span></th>
				<th><span>Members</span></th>
				<th><span>Creator</span></th>
				<th><span>Created</span></th>
			</tr>
		</thead>
		<tbody>
			<% unless authed_user.organizations.any? %>
			<tr id="empty-table">
				<td class="bg-warning" colspan="5">No organizations created yet.</td>
			</tr>
			<% end %>
			<% authed_user.organizations.each do |organization| %>
			<tr class="linked-row" data-href="<%= organization_path(organization) %>">
				<td><%= link_to organization.name, organization %></td>
				<td><%= link_to organization.lists.count, organization %></td>
				<td><%= link_to organization.memberships.count, organization %></td>
				<td><%= link_to organization.creator.full_name, organization %></td>
				<td><%= link_to "#{distance_of_time_in_words_to_now organization.created_at} ago", organization %> </td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/welcome/index.html.erb
<div class="hero">
	<div class="bgvideo">
		<video loop="loop" preload="auto" id="ipad-video" autoplay>
			<source src="//pure-gorge-8004.herokuapp.com/videos/Typing_on_Keyboard_2821_Videvo.mp4" type='video/mp4'>
				<source src="//pure-gorge-8004.herokuapp.com/videos/Typing_on_Keyboard_2821_Videvo.WebM" type='video/webm'>
				</video>
			</div>
			<div>
    
				<div class="container">

					<div class="pitch">
						<h1>LinkedIn&reg; Like A Boss</h1>
						<p class="lead">An app that helps power users save precious clicks and load times.</p>
						<a class="btn btn-large btn-primary" href="<%= sessions_linkedin_new_path %>">Get Started</a>
					</div>

				</div><!-- /.container -->
			</div><!-- /.hero -->
    
			<div class="container" id="below-video">    
				<div id="games">
					<h2>
						Our Features
					</h2>

             
					<div class="row">
						<div class="col-sm-4 game game-zombie">
							<h3><a href="#">WIP</a></h3>
							<p>One</p>
						</div>
						<div class="col-sm-4 game game-tower2">
							<a href="#">
								<h3>WIP</h3>
								<p>Two</p>
							</a>
						</div>
						<div class="col-sm-4 game game-zombie-arcade">
							<a href="#">
								<h3>WIP</h3>
								<p>Three</p>
							</a>
						</div>
					</div>
					<div class="row">
						<h3><a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">See More Features</a></h3>
          
						<div class="collapse" id="collapseExample">
							<div class="col-sm-4 game game-nuts">
								<a href="#">
									<h3>WIP</h3>
									<p>Four</p>
								</a>
							</div>
							<div class="col-sm-4 game game-tower1">
								<h3><a href="#">WIP</a></h3>
								<p>Five</p>
							</div>
							<div class="col-sm-4 game game-tower0">
								<a href="#">
									<h3>WIP</h3>
									<p>Six</p>
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-10 col-sm-offset-1 about-us">
					<h2>About us</h2>
					<h3>LiHero is a Web App and Mac App made in 2015.</h3>
					<p>Attention developers: we're looking to get help on our Assembly.com project!</p>
				</div>
      
			</div><!-- /.container -->
    
			<div id="carousel" class="carousel slide" data-ride="carousel">

				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<img src="img/slide4.jpg" alt="...">
						<div class="carousel-caption">
							...
						</div>
					</div>
					<div class="item">
						<img src="img/slide3.jpg" alt="...">
						<div class="carousel-caption">
							...
						</div>
					</div>
					<div class="item">
						<img src="img/slide2.jpg" alt="...">
						<div class="carousel-caption">
							...
						</div>
					</div>
					<div class="item">
						<img src="img/slide5.jpg" alt="...">
						<div class="carousel-caption">
							...
						</div>
					</div>
				</div>

				<!-- Controls -->
				<a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#carousel" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>