config/routes.rb
Rails.application.routes.draw do

  get 'linkedin/people'
  get 'linkedin/companies'

  resources :organizations do
    resources :memberships
    resources :lists do
      resources :leads
    end
  end

  resources :users do
    resources :oauths
  end

  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessions/linkedin/new', to: 'sessions#new_linkedin_auth'
  
  root 'welcome#index'
  get '/home', to: 'welcome#home'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :creator, class_name: 'User'
  has_many :memberships, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :users, through: :memberships
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :permalink, presence: true, uniqueness: { case_sensitive: false }
  validates :creator, presence: true  
  
  before_validation :autofill_permalink_if_blank
  
  after_create :create_default_membership
  
  def to_param
    self.permalink
  end
  
  def create_default_membership
    self.memberships.create!(
      user: self.creator,
      privileges: Membership::PRIVILEGE_CODES[:read_write_execute],
      creator: self.creator
    )
  end
  
  def autofill_permalink_if_blank
    return true unless self.permalink.blank? # Bypass if permalink is already set
    self.permalink = AutoPermalink::cleaned_deduped_permalink(self.class, self.name)
  end
  
  
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_filter :enforce_auth
  before_filter :set_authed_user_membership, only: [:show, :edit, :update, :destroy]
  before_filter :enforce_can_read, only: [:show]
  before_filter :enforce_can_write, only: [:edit, :update]
  before_filter :enforce_can_execute, only: [:destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = authed_user.organizations.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new(creator: authed_user)
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params.merge(creator: authed_user))

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = authed_user.organizations.find_by_permalink(params[:id])
      raise ActiveRecord::RecordNotFound unless @organization
    end

    def set_authed_user_membership
      @set_authed_user_membership = @organization.memberships.where(user_id: authed_user.id).first
      raise ActiveRecord::RecordNotFound unless @set_authed_user_membership
    end
  
    def enforce_can_read
      if !@set_authed_user_membership.read?
        render :text => "Sorry, you aren't authorized to access this page.", :status => :unauthorized
        return false
      else
        return true
      end
    end
    
    def enforce_can_write
      if !@set_authed_user_membership.write?
        render :text => "Sorry, you aren't authorized to access this page.", :status => :unauthorized
        return false
      else
        return true
      end
    end
    
    def enforce_can_execute
      if !@set_authed_user_membership.execute?
        render :text => "Sorry, you aren't authorized to access this page.", :status => :unauthorized
        return false
      else
        return true
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :permalink, :website)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
<% if @organization.errors.any? %>
<div id="error_explanation" class="alert alert-danger" role="alert">
	<strong><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</strong>

	<ul>
		<% @organization.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="row">
	<div class="form-group<%= f.object.errors[:name].empty? ? "" : " has-error has-feedback" %>">
		<%= f.label :name, { class: "control-label col-sm-2" } %>
		<div class="col-sm-10">
			<%= f.text_field :name, { class: "form-control title-control", autofocus: 'autofocus', placeholder: "Organization Name" } %>
		</div>
	</div>
</div>

<% if !f.object.new_record? %>
<div class="row">
	<div class="form-group<%= f.object.errors[:permalink].empty? ? "" : " has-error has-feedback" %>">
		<%= f.label :permalink, { class: "control-label col-sm-2" } %>
		<div class="col-sm-10">
			<%= f.text_field :permalink, { class: "form-control" } %>
		</div>
	</div>
</div>
<div class="row">
	<div class="form-group<%= f.object.errors[:website].empty? ? "" : " has-error has-feedback" %>">
		<%= f.label :website, { class: "control-label col-sm-2" } %>
		<div class="col-sm-10">
			<%= f.text_field :website, { class: "form-control" } %>
		</div>
	</div>
</div>
<% end %>
<div class="actions text-center">
	<%= f.submit class: "btn btn-success" %>
</div>
<% end %>

app/views/organizations/edit.html.erb
<% content_for :page_title do %>
Edit Organization - 
<% end %>
<div class="container">
<div class="page-header">
<h1>Editing Organization</h1>
</div>

<%= render 'form' %>

<div class="clearfix"></div>
<div class="pull-left">
<%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, @organization, class: "btn btn-default" %>
</div>
<div class="pull-right">
<%= link_to "<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> Delete organization...".html_safe, @organization, method: :delete, data: { confirm: "Are you sure you want to delete this organization?" }, class: "btn btn-danger" %>
</div>
</div>

app/views/organizations/index.html.erb
<% content_for :page_title do %>
Organizations - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>
			<div class="pull-left">
				<%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, home_path, class: "btn btn-default", title: "Back" %>
				&nbsp;
			</div>
			<div class="pull-right">
				<%= link_to "<span class=\"glyphicon glyphicon-plus-sign\" aria-hidden=\"true\"></span> New Organization".html_safe, [:new, :organization], class: "btn btn-success" %>
			</div>
			Listing Organizations
		</h1>
	</div>
	<table class="table table-striped table-hover tablesorter" id="Organizations-table">
		<thead>
			<tr>
				<th><span>Name</span></th>
				<th><span>Lists</span></th>
				<th><span>Members</span></th>
				<th><span>Creator</span></th>
				<th><span>Created</span></th>
			</tr>
		</thead>
		<tbody>
			<% unless @organizations.any? %>
			<tr id="empty-table">
				<td class="bg-warning" colspan="5">No organizations created yet.</td>
			</tr>
			<% end %>
			<% @organizations.each do |organization| %>
			<tr class="linked-row" data-href="<%= organization_path(organization) %>">
				<td><%= link_to organization.name, organization %></td>
				<td><%= link_to organization.lists.count, organization %></td>
				<td><%= link_to organization.memberships.count, organization %></td>
				<td><%= link_to organization.creator.full_name, organization %></td>
				<td><%= link_to "#{distance_of_time_in_words_to_now organization.created_at} ago", organization %> </td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/organizations/new.html.erb
<% content_for :page_title do %>
Create Organization - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>
			New Organization
		</h1>
	</div>

	<%= render 'form' %>

	<div class="clearfix"></div>
	<%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, organizations_path, class: "btn btn-default" %>
</div>

app/views/organizations/show.html.erb
<% content_for :page_title do %>
<%= @organization.name%> - Organization Details - 
<% end %>
<div class="container">
	<div class="page-header">
		<h1>
			<div class="pull-left">
				<%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, organizations_path, class: "btn btn-default", title: "Back to organizations" %>
				&nbsp;
			</div>
			<div class="pull-right">
				<%= link_to "<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> Edit".html_safe, edit_organization_path(@organization), class: "btn btn-warning" %>
			</div>
			Organization Details
		</h1>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Name</label>
		<div class="col-sm-9"><strong><%= @organization.name %></strong></div>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">&nbsp;</label>
		<div class="col-sm-9"><small><span class="text-muted"><%= organizations_url %>/</span><%= @organization.permalink %> (<%= link_to 'link', @organization %>)</small></div>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Website</label>
		<div class="col-sm-9"><%= @organization.website.blank? ? '[n/a]' : link_to(@organization.website,@organization.website) %></div>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Created</label>
		<div class="col-sm-9"><%= distance_of_time_in_words_to_now @organization.created_at %> ago</div>
	</div>

	<div class="row">
		<label class="col-sm-3 text-right text-muted">Created By</label>
		<div class="col-sm-9"><%= @organization.creator.full_name %></div>
	</div>
	
	<hr>
	
	<div>
		<h2>
			<div class="pull-right">
				<a href="<%= new_organization_membership_path(@organization) %>" class="btn btn-info">Add a Member</a>
			</div>
			<%= link_to 'Team Members', organization_memberships_path(@organization) %> <span class="label label-default"><%= @organization.memberships.count %></span>
		</h2>
	</div>
	
	<div>
		<h2>
			<div class="pull-right">
				<a href="<%= new_organization_list_path(@organization) %>" class="btn btn-info">Add a List</a>
			</div>
			<%= link_to 'Lists', organization_lists_path(@organization) %> <span class="label label-default"><%= @organization.lists.count %></span>
		</h2>
	</div>
</div>